### ISSUE TITLE
Getting Invalid Data Format errors

### ISSUE THREAD

**Issue by timj** [ecdye/macSubtitleOCR#13] opened 2024-09-30 00:02 UTC
Thank you so much for working on a tool like this. I've been looking around for a PGS to SRT convertor for a while and had considered learning Swift purely to use the Apple OCR library (I'm mainly a Python guy). I was looking at installing .NET and trying to get SubtitleEdit  to work in batch mode and then I saw your comment pointing to this repo.

I've built it just fine (I just updated to Sequoia on M1 Ultra) but haven't yet found a file that it works with. I've tried a few MKV files (and a .sup file I extracted with `mkvextract` and I'm getting errors like:

> Invalid Data Segment Length: 7
> Error: invalidFormat

or 

> Invalid objectDataLength: 66382 <= 65512
> Error: invalidFormat

(the latter came from ODS.swift where I added a debug print).

Is there any information I can send you about these files that would help debug?

**Comment by timj** [comment] 2024-09-30 04:10
(the MKV files are all made with MakeMKV)

**Comment by ecdye** [comment] 2024-09-30 15:42
Out of curiosity, if you compile it and run it on the included test files (which are from the Sintel Blender open movie) do those work?

**Comment by ecdye** [comment] 2024-09-30 15:45
OK, I have a theory, I think you might not have Swift 6 support on your compiler. Have you tried updating to Xcode 16?

As a second step, you could try using the nightly build binary.

**Comment by timj** [comment] 2024-09-30 15:47
```$ swift --version
swift-driver version: 1.115 Apple Swift version 6.0 (swiftlang-6.0.0.9.10 clang-1600.0.26.2)
Target: arm64-apple-macosx15.0```

I don't technically have XCode installed, I use the command line tools. I'll look at the binary.

**Comment by timj** [comment] 2024-09-30 15:52
Downloaded the nightly. Same result (once I removed the quarantine bit).

**Comment by ecdye** [comment] 2024-09-30 16:07
@timj I just found this forum post, it might be part of the issue, I'm not sure why mine was working as I don't recall installing the version from Swift.org but its worth a shot.
It probably won't fix the other errors, but at least that should let you test and see if the test files work.

https://forums.swift.org/t/error-no-such-module-testing/74784/4

**Comment by timj** [comment] 2024-09-30 16:20
Ok. I tried the command on a bunch of MKV files I had lying around and the good news is that it does seem to work for a lot of them. Just not the ones I tried last night.

**Comment by ecdye** [comment] 2024-09-30 16:37
Ok, so I think I figured out what the issue is, I never implemented support for multi segment ODS, because none of my test files had them. I just pushed some commits that *hopefully* add support for them, but I still don't have any test files, so it may or may not actually work. Give it a try and let me know.

**Comment by timj** [comment] 2024-09-30 16:49
Thanks. Didn't help. I will see if I can extract a very small failing .sup file for you.

**Comment by ecdye** [comment] 2024-09-30 16:55
> Thanks. Didn't help. I will see if I can extract a very small failing .sup file for you.

If you can, that would help a lot.

**Closed** 2024-10-01 05:05 UTC
Labels: bug

**Comment by timj** [comment] 2024-10-01 22:36
Everything worked except one file that, it turned out has a PGS segment but no actual content. SubTools did load it without complaint (with no actual subtitles). The error status meant my batch script fell over so if you are interested in this tiny issue the (small) file is attached.

[nosubs.sup.gz](https://github.com/user-attachments/files/17217312/nosubs.sup.gz)

**Comment by timj** [comment] 2024-10-01 22:37
I will say that the program worked great though. Looking forward to #7 since vosub2srt is annoying to build.

**Comment by ecdye** [comment] 2024-10-02 01:24
> I will say that the program worked great though. Looking forward to #7 since vosub2srt is annoying to build.

Oh believe me, I know. I had to make custom changes to it years ago to make it work and that was what I was relying on up until I finally broke down and dug myself this rabbit hole.

I'll take a look at the no subs one. I suspect that one is probably a pretty easy fix, I'm probably throwing an error when I should just issue a warning and skip.
